spring:
  application:
    name: config-server
  cloud:
    consul:
      host: 192.168.0.7
      port: 8500
      discovery:
        hostname: 192.168.0.6
    config:
      server:
        jdbc:
          sql: SELECT akey,avalue FROM tb_config_server WHERE application=? AND aprofile=? AND label=?
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zyconfig??useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: zhouyu2001cloud
  profiles:
    active: jdbc
server:
  port: 9000
